# Generated by Django 4.2.13 on 2025-02-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_featured_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
