# Generated by Django 4.2.13 on 2024-06-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
