# Generated by Django 4.2.13 on 2024-06-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='recipecomment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.IntegerField(choices=[(0, 'International'), (1, 'Mediterranean'), (2, 'Asian'), (3, 'Middle-Eastern'), (4, 'European'), (5, 'African'), (6, 'American'), (7, 'Latin-American'), (8, 'Caribbean')], default=0),
        ),
    ]
