# Generated by Django 4.2.13 on 2024-07-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_cuisine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeComment',
        ),
    ]
